#ifndef BLADERF_CLI_VERSION_H__
#define BLADERF_CLI_VERSION_H__

#define BLADERF_CLI_VERSION       "1.9.0-git-4f3fcb2e-dirty"

#define BLADERF_CLI_VERSION_MAJOR 1
#define BLADERF_CLI_VERSION_MINOR 9
#define BLADERF_CLI_VERSION_PATCH 0

#endif
